### ISSUE TITLE
Can't install without errors

### ISSUE THREAD

**Issue by JohnSmall** [0xSatellites/satellites#657]
Using node v12.9.1, npm 6.10.3 on MacOS 10.14.5 I tried to install by following the instructions. 

at `npm install` I get

      8 warnings and 7 errors generated.
      make: *** [Release/obj.target/scrypt/src/node-boilerplate/scrypt_params_async.o] Error 1
      gyp ERR! build error 
      gyp ERR! stack Error: `make` failed with exit code: 2
      gyp ERR! stack     at ChildProcess.onExit 
      (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:196:23)
      gyp ERR! stack     at ChildProcess.emit (events.js:209:13)
      gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
      gyp ERR! System Darwin 18.6.0
      gyp ERR! command "/usr/local/Cellar/node/12.9.1/bin/node" 
      "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
      gyp ERR! cwd /Users/john/ruby_projects/research/satellites/templates/node_modules/scrypt
      gyp ERR! node -v v12.9.1
      gyp ERR! node-gyp -v v5.0.3
      gyp ERR! not ok 
      npm WARN @nuxtjs/vuetify@0.5.5 requires a peer of vuetify-loader@^1.2.1 but none is 
      installed. You must install peer dependencies yourself.
      npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 
      (node_modules/ganache-core/node_modules/fsevents):
       npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 install: `node 
       install`
       npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
       npm WARN optional SKIPPING OPTIONAL DEPENDENCY: scrypt@6.0.3 
      (node_modules/ganache-core/node_modules/scrypt):
      npm WARN optional SKIPPING OPTIONAL DEPENDENCY: scrypt@6.0.3 install: `node-gyp 
     rebuild`
      npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1
      npm ERR! code ELIFECYCLE
       npm ERR! errno 1
      npm ERR! scrypt@6.0.3 install: `node-gyp rebuild`
      npm ERR! Exit status 1
      npm ERR! 
      npm ERR! Failed at the scrypt@6.0.3 install script.
      npm ERR! This is probably not a problem with npm. There is likely additional logging output 
     above.

Any idea how to proceed?

**Comment by kolife01** [comment]
We found that there was a problem when using node 12.x.
We have confirmed that it works well using node v11.x.
Please use node v11.x until solved this problem.

**Comment by alpimany** [comment]
i've faced this issue since a while, i don't relay know what is the problem but i think nuxtjs is using a npm package which requires node-gyp.
i solved this by installing node-gyp following the [node-gyp installations steps](https://github.com/nodejs/node-gyp#installation.)
